---
title: "de Parscau"
author: "Gwenn de Parscau"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
library(readr)
here::i_am("grades.Rproj")
library(here)
grades <- read_csv("grades(1).csv")
```

```{r}
print("the data set countains")
nrow(grades)
print("grades")
```

```{r}
grades |>
  group_by(group) |>
  distinct(id) |>
  slice_tail(n=5) |>
  knitr::kable() 
```

```{r}
library(ggplot2)
ggplot(grades, aes(x=group))+
    geom_bar()
```
```{r}
hacking_grades <-
  grades |>
  filter(str_detect(course, "Hacking"))
```

```{r}
grades |>
  group_by(group) |>
  summarise(mean_hacking_grades = mean(hacking_grades))
```

```{r}
ggplot(grades, aes(x=mean_hacking_grades, y = group))+
  geom_col()
```

```{r}
grades |>
  group_by(id, group) |>
  summarise(nb_grades = n()) |>
  slice_tail(n = 5)
```

```{r}
grades |>
  group_by(id) |>
  summarise(min = min(grade), max = max(grade),mean = mean(grade), median = median(grade) ) |>
  knitr::kable()
```


```{r}
nb_grades <- grades |>
  group_by(id, group) |>
  mutate(nb_grades=n())
data_frame_vr_ar <- 
  nb_grades |>
  filter(str_detect(course, "Virtual")) |>
  group_by(id, group, nb_grades) |>
  slice_tail(n = 5)|> print(data_frame_vr_ar)
```

```{r}
data_frame_vr_ar |>
  group_by(grade) |>
  summarise(nb_students = sum(id))
ggplot(data_frame_vr_ar, aes(x=grade))+
  geom_bar()
```

```{r}
ggplot(data_frame_vr_ar, aes(x=grade))+
  geom_bar()+
  facet_wrap(~group)
```


